package common;

import server.Server;

import java.io.*;
import java.util.LinkedHashMap;

/**
 * Reads a configuration file to setup ingredients, dishes, postcodes, users, orders, stock, staff and drones. This
 * can also be used to read a backup file in the event of a system failure (file generated by DataPersistence).
 *  @author Jack Corbett
 */
public class Configuration {

    /**
     * Read the file and create objects on the server.
     * @param filename The file to read configuration settings from.
     * @param server A reference to the server object to enable access to it's methods.
     */
    public Configuration(String filename, Server server) {
        try {
            InputStream inputStream = this.getClass().getResourceAsStream(filename);

            if (inputStream != null) {
                InputStreamReader inputStreamReader = new InputStreamReader(inputStream);
                BufferedReader br = new BufferedReader(inputStreamReader);

                String string;
                // Loop for each line of the file
                while ((string = br.readLine()) != null) {
                    // Skip if it's an empty line
                    if (string.equals("")) continue;

                    // Split on : to separate the instruction from data
                    String[] strings = string.split(":");

                    switch (strings[0]) {
                        case "SUPPLIER":

                            server.addSupplier(strings[1], Integer.parseInt(strings[2]));

                            break;
                        case "INGREDIENT":

                            Supplier ingSupplier = null;
                            // Find the supplier object for that ingredient
                            for (Supplier supplier : server.getSuppliers()) {
                                if (supplier.getName().equals(strings[3])) ingSupplier = supplier;
                            }
                            server.addIngredient(strings[1], strings[2], ingSupplier,
                                    Integer.parseInt(strings[4]), Integer.parseInt(strings[5]));

                            break;
                        case "DISH":

                            Dish dish = server.addDish(strings[1], strings[2],
                                    Double.parseDouble(strings[3]),
                                    Integer.parseInt(strings[4]),
                                    Integer.parseInt(strings[5]));

                            // Split into pairs of quantities and ingredients
                            String[] recipeElements = strings[6].split(",");

                            for (String recipeElement : recipeElements) {
                                // Split into ingredient and quantity
                                String[] element = recipeElement.split(" \\* ");

                                // Pointer to the ingredient
                                Ingredient recipeIngredient = null;

                                for (Ingredient ingredient : server.getIngredients()) {
                                    if (ingredient.getName().equals(element[1])) recipeIngredient = ingredient;
                                }

                                server.addIngredientToDish(dish, recipeIngredient,
                                        Double.parseDouble(element[0]));
                            }

                            break;
                        case "POSTCODE":

                            server.addPostcode(strings[1], Integer.parseInt(strings[2]));

                            break;
                        case "USER":

                            Postcode userPostcode = null;

                            for (Postcode postcode : server.getPostcodes()) {
                                if (postcode.getName().equals(strings[4])) userPostcode = postcode;
                            }

                            server.users.add(new User(strings[1], strings[2], strings[3], userPostcode));

                            break;
                        case "ORDER":

                            LinkedHashMap<Dish, Number> order = new LinkedHashMap<>();

                            // Further split to separate the dishes in the order
                            String[] orderElements = strings[2].split(",");

                            for (String orderElement : orderElements) {
                                // Split to separate the name and quantity
                                String[] element = orderElement.split(" \\* ");

                                Dish orderDish = null;

                                for (Dish dishO : server.getDishes()) {
                                    if (dishO.getName().equals(element[1])) orderDish = dishO;
                                }

                                order.put(orderDish, Integer.parseInt(element[0]));
                            }

                            User orderUser = null;

                            for (User user : server.users) {
                                if (user.getName().equals(strings[1])) orderUser = user;
                            }

                            // Create the new order and add it to the orders array list and order queue for the drones.
                            Order newOrder = new Order(orderUser, order);
                            server.orders.add(newOrder);
                            server.orderQueue.add(newOrder);

                            break;
                        case "STOCK":

                            Dish dishForStock = null;
                            Ingredient ingredientForStock = null;

                            // Search through both the dishes and ingredients to check if the name matches
                            for (Dish dishStock : server.getDishes()) {
                                if (dishStock.getName().equals(strings[1])) dishForStock = dishStock;
                            }
                            for (Ingredient ingredientStock : server.getIngredients()) {
                                if (ingredientStock.getName().equals(strings[1])) ingredientForStock = ingredientStock;
                            }

                            // Add it to the stock using the server
                            if (dishForStock != null) server.setStock(dishForStock, Integer.parseInt(strings[2]));
                            if (ingredientForStock != null) server.setStock(ingredientForStock,
                                    Integer.parseInt(strings[2]));

                            break;
                        case "STAFF":

                            server.addStaff(strings[1]);

                            break;
                        case "DRONE":

                            server.addDrone(Integer.parseInt(strings[1]));

                            break;
                    }
                }
            }
        } catch (IOException e) {
            System.err.println("Failed to read from config file");
        }
    }
}
